[build-system]
requires = ["setuptools", "wheel", "cement", "pandas"]

[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | spiral\/cli\/templates\/generate
)/
'''
